services:
  redis-test:
    image: redis:latest
    container_name: "redis-test"
    ports:
      - 6379:6379

  redis-dev:
    image: redis:latest
    container_name: "redis-dev"
    ports:
      - 6380:6379
    volumes:
      - redis_data:/data

  postgres-test:
    image: postgres:latest
    container_name: "postgres-test"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: rootpassword
    ports:
      - "5433:5432"

  postgres-dev:
    image: postgres:latest
    container_name: "postgres-dev"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  redis_data:
  postgres_data:
