// Generated by https://quicktype.io

import { ObjectId } from "mongodb";

export interface Product {
  _id: ObjectId;
  name: string;
  brand: string;
  description: string;
  image: string;
  mpns: string[];
  gtins: string[];
  retailers: Retailer[];
  category: Category | undefined;
}

export interface Category {
  main: number;
  sub: number;
  product: number;
}

export interface Retailer {
  name: string;
  price: number;
  sku: string;
  url: string;
  category: string;
}
